""""
DPI - принцип инверсии зависимости
"""
from typing import Any, Protocol


class LLMGateway(Protocol):
    async def generate(self, messages: list[dict[str, str]], temperature: float) -> str: ...


class DialogStore(Protocol):
    async def ensure_user_settings(
        self, user_id: int, *, mode: str = ..., temperature: float = ...
    ) -> None: ...

    async def get_user_settings(self, user_id: int) -> Any: ...

    async def set_temperature(self, user_id: int, temperature: float) -> None: ...

    async def set_mode(self, user_id: int, chat_id: int, mode: str, temperature: float) -> None: ...

    async def get_history(
        self, chat_id: int, limit: int = ..., max_chars: int = ...
    ) -> list[dict[str, str]]: ...

    async def save_exchange(self, chat_id: int, question: str, answer: str) -> None: ...

    async def clear_history(self, chat_id: int) -> int: ...
